### ISSUE TITLE
Error while running on Windows 10 

### ISSUE THREAD

**Issue by praveen-pawar16** [coady/graphique#6]
I am trying to run graphique on Windows 10. Here`s the issues.

Refer point 1 where command used to run server locally. It resulted in "ModuleNotFoundError: No module named 'graphique.arrayed'".

When I try to build it with "setup.py". It resulting in other issue. Refer 2

1. >uvicorn graphique.service:app
Traceback (most recent call last):
  File "C:\py10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\py10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\py10\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
  File "C:\py10\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\py10\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\py10\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\py10\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\py10\lib\site-packages\uvicorn\main.py", line 425, in main
    run(app, **kwargs)
  File "C:\py10\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "C:\py10\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\py10\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\py10\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\py10\lib\site-packages\uvicorn\server.py", line 76, in serve
    config.load()
  File "C:\py10\lib\site-packages\uvicorn\config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\py10\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\py10\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\py10\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\My Drive\master-data-api\graphique\.\graphique\service.py", line 14, in <module>
    from .core import Column as C, ListChunk, Table as T
  File "G:\My Drive\master-data-api\graphique\.\graphique\core.py", line 17, in <module>
    from .arrayed import group_indices  # type: ignore
ModuleNotFoundError: No module named 'graphique.arrayed'

2. >setup.py build
running build
running build_py
running build_ext
building 'graphique.arrayed' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\py10\include -IC:\py10\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /EHsc /Tpgraphique/arrayed.cpp /Fobuild\temp.win-amd64-3.10\Release\graphique/arrayed.obj -std=c++11
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
arrayed.cpp
c1xx: fatal error C1083: Cannot open source file: 'graphique/arrayed.cpp': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by coady** [comment]
Are you trying to run from a git checkout?

1. If you're just trying to run it, there are [wheels for windows](https://pypi.org/project/graphique/#files), so `pip install graphique[server]` should work.
2. If you're trying to build from source, the [source distribution](https://files.pythonhosted.org/packages/75/29/59470998dbca8df01aeb34be9ff86c2c6c2de9f9d96f6583426848a4cd91/graphique-0.6.zip) has the `.cpp` generated (the second error).
3. If you're trying to build it from git source, then `cython` is required.

**Comment by praveen-pawar16** [comment]
Appreciate your response on it. The links are verify helpful. Some finding from which will be helpful on future.
1. If you're just trying to run it, there are wheels for windows, so pip install graphique[server] should work.
- Here I have to create a virtual environment to run it on local windows machine


2. If you're trying to build from source, the source distribution has the .cpp generated (the second error).
- It`s working with the source code provided with the given link.

3. If you're trying to build it from git source, then cython is required.
- Yet to try this. I`ll let you know in case of any issues.

Closing this issue as it`s working on Windows machine when "pip install graphique[server]" installed on python virtual environment.
